[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CTkPlus"
version = "1.0.4"
description = "vidgets for customtkinter"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "customtkinter",
]

[project.urls]
Homepage = "https://github.com/w1n4a/CTkPlus"
Repository = "https://github.com/w1n4a/CTkPlus"

[project.scripts]
ctkplus-wget = "ctkplus.wget:start"
