name: Update README Table

on:
  push:
    paths:
      - 'wget-json.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate HTML Table from JSON
        run: |
          TABLE='<table width="100%"><thead><tr><th align="left" width="30%">Widget</th><th align="left">Description</th></tr></thead><tbody>'
          while read -r key value; do
            if [[ ! -z "$key" && ! -z "$value" ]]; then
              TABLE="$TABLE<tr><td><strong>$key</strong></td><td>$value</td></tr>"
            fi
          done < <(jq -r 'to_entries | .[] | "\(.key) \(.value)"' wget-json.json)
          TABLE="$TABLE</tbody></table>"
          
          sed -i '/<!-- WIDGET_TABLE_START -->/,/<!-- WIDGET_TABLE_END -->/{//!d}' README.md
          sed -i '/<!-- WIDGET_TABLE_START -->/a \'"$TABLE"'' README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Auto-update README widget table [skip ci]" && git push
